<template>
	<div class="support">
		<div class="container" style="border-top: 1px solid #eee; padding: 40px 0">
			<div style="padding: 10px 0">Lorem ipsum dolor sit amet. Enim ipsam voluptatem, quia. Animi, id est eligendi optio. Deserunt mollitia animi, id est eligendi optio, cumque nihil. Modi tempora incidunt, ut labore et accusamus et quas molestias excepturi sint. Aut rerum hic tenetur a sapiente delectus, ut et aut perferendis doloribus. Neque porro quisquam est, qui ratione voluptatem accusantium doloremque laudantium totam. Omnis voluptas assumenda est, omnis voluptas assumenda est. Sunt, explicabo velit esse, quam nihil molestiae. Eius modi tempora incidunt, ut aut perferendis doloribus asperiores repellat.. Ea voluptate velit esse quam. Fugiat, quo minus id, quod maxime placeat, facere possimus, omnis voluptas sit. Voluptatum deleniti atque corrupti, quos dolores et quas molestias excepturi sint obcaecati. Aperiam eaque ipsa, quae ab illo inventore. Consequuntur magni dolores et molestiae consequatur, vel eum iure. Harum quidem rerum necessitatibus saepe eveniet, ut enim ad minima veniam. Molestiae consequatur, vel illum, qui placeat, facere possimus. Culpa, qui dolorem eum iure. Totam rem aperiam eaque ipsa, quae ab illo inventore veritatis.</div>
			<br>
			<div style="padding: 10px 0">Quia non provident, similique sunt. Est, qui delectus, ut perspiciatis unde. Obcaecati cupiditate non numquam eius modi. Voluptates repudiandae sint et accusamus. Accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae. Corporis suscipit laboriosam, nisi ut perspiciatis, unde omnis dolor sit. Molestias excepturi sint, obcaecati cupiditate non recusandae molestias excepturi. Exercitationem ullam corporis suscipit laboriosam, nisi ut et dolore. Aliquid ex ea commodi autem quibusdam. Maiores alias consequatur aut perferendis doloribus asperiores repellat. numquam eius. Dolor repellendus eveniet, ut labore. Officia deserunt mollitia animi, id est laborum et dolorum. Sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa quae. Iusto odio dignissimos ducimus, qui ratione voluptatem accusantium doloremque laudantium. Accusantium doloremque laudantium, totam rem aperiam eaque ipsa. Ea commodi autem quibusdam et harum. Et voluptates repudiandae sint et molestiae consequatur, vel eum fugiat. Soluta nobis est et accusamus et molestiae non numquam. Possimus, omnis dolor sit, aspernatur aut reiciendis. Similique sunt in ea voluptate velit esse, quam nihil molestiae non. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio minima laborum soluta sunt voluptates assumenda optio mollitia nobis ea aut, debitis magnam ipsum nam eveniet ducimus aspernatur labore, voluptatibus officiis?</div>
			<br>
			<div style="padding: 10px 0">Dignissimos ducimus, qui in culpa, qui dolorem. Illo inventore veritatis et expedita distinctio. Impedit, quo minus id, quod maxime placeat, facere possimus omnis. Tempore, cum soluta nobis. Voluptas assumenda est, omnis iste natus error sit voluptatem. Quo voluptas nulla vero eos et dolore. Voluptates repudiandae sint et iusto odio dignissimos ducimus. Earum rerum facilis est et aut odit aut rerum necessitatibus saepe eveniet. Maxime placeat, facere possimus, omnis dolor. Harum quidem rerum necessitatibus saepe eveniet, ut labore et accusamus. Omnis voluptas assumenda est. Dolores eos, qui dignissimos ducimus, qui. Nisi ut labore et quas molestias excepturi sint, obcaecati cupiditate. Incidunt, ut perspiciatis, unde omnis dolor. Aliquam quaerat voluptatem accusantium doloremque laudantium, totam. Quo voluptas assumenda est, omnis iste natus error. Impedit, quo voluptas assumenda est, omnis iste natus error sit voluptatem. Consequatur, vel illum, qui blanditiis praesentium voluptatum deleniti atque. Molestiae non recusandae nemo enim. Sequi nesciunt, neque porro quisquam est, qui ratione voluptatem accusantium doloremque.</div>
		</div>
	</div>
</template>

<style lang="sass">
.support
	color: gray
</style>